%global tl_name montex
%global tl_revision 29349
%global tl_version IVu.04.092

Name:		texlive-%{tl_name}
Epoch:		1
Version:	%{tl_version}
Release:	%{tl_revision}.1
Summary:	Mongolian LaTeX
Group:		Publishing
URL:		https://www.ctan.org/tex-archive/language/mongolian/montex
License:	gpl
Source0:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/montex.r%{tl_revision}.tar.xz
Source1:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/montex.doc.r%{tl_revision}.tar.xz
BuildArch:	noarch
BuildSystem:	texlive
Requires:	texlive(cbfonts)
Requires:	texlive-tlpkg
Provides:	texlive(%{tl_name}) = %{version}

%description
MonTeX provides Mongolian and Manju support for the TeX/LaTeX community.
Mongolian is a language spoken in North East Asia, namely Mongolia and
the Inner Mongol Autonomous Region of China. Today, it is written in an
extended Cyrillic alphabet in Mongolia whereas the Uighur writing
continues to be in use in Inner Mongolia, though it is also, legally
speaking, the official writing system of Mongolia. Manju is another
language of North East Asia, belonging to the Tungusic branch of the
Altaic languages. Though it is hardly spoken nowadays, it survives in
written form as Manju was the native language of the rulers of the Qing
dynasty (1644-1911) in China. Large quantities of documents of the
Imperial Archives survive, as well as some of the finest dictionaries
ever compiled in Asia, like the Pentaglot, a dictionary comprising
Manju, Tibetan, Mongolian, Uighur and Chinese. MonTeX provides all
necessary characters for writing standard Mongolian in Cyrillic and
Classical (aka Traditional or Uighur) writing, and Manju as well as
transliterated Tibetan texts, for which purpose a number of additional
characters was created. In MonTeX, both Mongolian and Manju are entered
in romanized form. The retransliteration (from Latin input to Mongolian
and Manju output) is completely realized in TeX/Metafont so that no
external preprocessor is required. Please note that most of the enhanced
functions of MonTeX require a working e-LaTeX environment. This is
especially true when compiling documents with Mongolian or Manju as the
main document language. It is recommended to choose pdfelatex as the
resulting PDF files are truly portable. Vertical text generated by
MonTeX is not supported in DVI.


%install -a
mkdir -p %{buildroot}%{_texmf_updmap_d}
cat > %{buildroot}%{_texmf_updmap_d}/%{tl_name} <<'TL_DROPIN_EOF'
# from montex:
MixedMap mongolian.map
TL_DROPIN_EOF
